services:
  copito-db:
    container_name: copito_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}

  copito-web:
    depends_on:
      - copito-db
    restart: always
    build: .
    volumes:
      - ./pages:/app/pages
    ports:
      - "${PORT}:3000"
    environment:
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${DATABASE_URL}