export type EntityType = {
  __typename?: string,
  name: string,
  address: string,
  category: string,
  city: string,
  committee: boolean,
  commune: number,
  email: string,
  neighborhood: string,
  phone: number,
  position: string,
  acopio: boolean,
  acopioName?: string,
  prae?: boolean,
  praeName?: string,
  proceda?: string,
  procedaProject?: string,
  attachment: string,
}